### PR TITLE
Expand CPython support classifiers to cover testing up through 3.11

### PR DESCRIPTION
**Pull request by altendky**

### CODE REVIEW

**Comment by altendky** [comment]
It also seems to be working with PyPy.  Do you want to add reference to that as well?  I understand maybe not wanting to 'promise' that even if it happens to work now.

**Comment by frispete** [comment]
For now, CPythons are fine. Wouldn't the CI test PyPy anyway?

**Comment by altendky** [comment]
The present setup does test PyPy, yes.  But once you promise there's a little more 'responsibility' to _keep_ it working instead of letting it break.  Anyways, I'll leave that alone for now.  It's mostly just human reference anyways, not used for 'can pypy install this package'.

**Comment by frispete** [comment]
Thank you for your support on this. Much appreciated!

**Comment by altendky** [comment]
Just trying to help make our dependency a bit more robust.  Happy to help.

**Pull request merged**
